#!/usr/bin/env python3
"""Generate docs/enterprise/FEATURES.md from the feature registry (backend/features.py).

    python3 scripts/gen-features-doc.py          # write the file
    python3 scripts/gen-features-doc.py --check  # exit 1 when the file is stale (CI, tests)

The registry is the source of truth: never edit FEATURES.md by hand.
"""
from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "enterprise" / "FEATURES.md"
# importing backend modules on a host must never touch real data (rule of 07.10.2026)
os.environ.setdefault("SOKKAN_DATA_DIR", tempfile.mkdtemp(prefix="sokkan-featdoc-"))
sys.path.insert(0, str(ROOT / "backend"))

import features as F  # noqa: E402


def _default(v, f: F.Feature | None = None) -> str:
    if f is not None and f.kind == "integration":
        return "if configured"
    if f is not None and f.kind == "invariant":
        return "always"
    return "auto" if v == "auto" else ("on" if v else "off")


def _vars(f: F.Feature) -> str:
    if f.kind in ("integration", "invariant"):
        return ", ".join(f"`{c}`" for c in f.config) or "—"
    out = []
    for v in f.vars:
        s = f"`{v.name}`"
        if v.legacy and v.name != f.canonical_var:
            s += " (legacy" + (f": {v.note}" if v.note else "") + ")"
        out.append(s)
    return "<br>".join(out) or "—"


def _ids(xs) -> str:
    return ", ".join(f"`{x}`" for x in xs) or "—"


def render() -> str:
    L: list[str] = []
    w = L.append
    w("<!-- GENERATED by scripts/gen-features-doc.py from backend/features.py — do not edit. -->")
    w("# SOKKAN features")
    w("")
    w("SOKKAN Enterprise is **the same open-source app**, not a fork. Every capability below is a "
      "feature of one registry (`backend/features.py`): it can be turned on or off on its own, "
      "its dependencies are declared, and the edition only changes **defaults**.")
    w("")
    w("## How a feature is decided")
    w("")
    w("1. `SOKKAN_EDITION` = `community` (default) or `enterprise` picks the column of defaults.")
    w("2. `SOKKAN_FEATURE_<ID>=1|0` turns a feature on or off. The variables used before the "
      "registry (marked *legacy*) are still read, after the canonical one: an existing "
      "installation changes nothing. An empty value counts as unset.")
    w("3. *integration* features are on when their service is configured; *invariant* features "
      "are security properties, always on; *planned* features are declared for the roadmap and "
      "stay off whatever the environment says.")
    w("4. A feature whose required feature is off, or whose conflicting feature is on, is "
      "**turned off** with its reason. The API always starts; a feature is never half on. If "
      "it had been asked for explicitly, the API logs `[features] <id> is OFF: <reason>` at "
      "startup and Profile → Features shows it in red.")
    w("")
    w("State on a running instance: `GET /api/features` (`registry`) or Profile → Features "
      "(admins).")
    w("")
    w("## Registry")
    w("")
    w("| Feature | Status | Kind | Community | Enterprise | Requires | Conflicts | Switch |")
    w("|---|---|---|---|---|---|---|---|")
    for f in F.REGISTRY:
        w(f"| [`{f.id}`](#{f.id}) {f.title} | {f.status}"
          f"{(' (' + f.target + ')') if f.target else ''} | {f.kind} | "
          f"{_default(f.defaults['community'], f)} | {_default(f.defaults['enterprise'], f)} | "
          f"{_ids(f.requires)} | {_ids(f.conflicts)} | {_vars(f)} |")
    w("")
    w("## Dependency graph")
    w("")
    w("Solid arrow = *requires*; dotted = *conflicts with*. Dashed boxes are planned.")
    w("")
    w("```mermaid")
    w("graph LR")
    for f in F.REGISTRY:
        w(f'  {f.id}["{f.title}"]')
    for f in F.REGISTRY:
        for d in f.requires:
            w(f"  {f.id} --> {d}")
    done: set[frozenset] = set()
    for f in F.REGISTRY:
        for c in f.conflicts:
            k = frozenset((f.id, c))
            if k not in done:
                done.add(k)
                w(f"  {f.id} -.-x {c}")
    w("  classDef planned stroke-dasharray: 5 5,color:#888;")
    w("  classDef integration fill:#eef6ff;")
    w("  classDef invariant fill:#eaf7ea;")
    for kind in ("planned", "integration", "invariant"):
        ids = [f.id for f in F.REGISTRY if f.kind == kind]
        if ids:
            w(f"  class {','.join(ids)} {kind};")
    w("```")
    w("")
    w("## Features")
    for f in F.REGISTRY:
        w("")
        w(f"### {f.id}")
        w("")
        w(f"**{f.title}** — {f.status}{(' for ' + f.target) if f.target else ''}, {f.kind}.")
        w("")
        w(f.description)
        w("")
        w(f"- Defaults: community **{_default(f.defaults['community'], f)}**, "
          f"enterprise **{_default(f.defaults['enterprise'], f)}**")
        if f.requires:
            w(f"- Requires: {_ids(f.requires)}")
        req_by = [g.id for g in F.REGISTRY if f.id in g.requires]
        if req_by:
            w(f"- Required by: {_ids(req_by)}")
        if f.conflicts:
            w(f"- Conflicts with: {_ids(f.conflicts)}")
        w(f"- {'Configuration' if f.kind in ('integration', 'invariant') else 'Switch'}: "
          f"{_vars(f).replace('<br>', ', ')}")
        if f.forced:
            w("- Forced on for SOKKAN Cloud managed instances (`SOKKAN_TIER` set).")
        if f.doc:
            w(f"- Doc: [{f.doc}](../../{f.doc})")
    w("")
    return "\n".join(L)


def main() -> int:
    errs = F.validate_registry()
    if errs:
        print("registry invalid:\n  " + "\n  ".join(errs), file=sys.stderr)
        return 2
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run scripts/gen-features-doc.py",
                  file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
