"""Incremental indexer of a memory corpus, written against the ``Store`` interface.

One pass:

1. (optional) ``core.normalize`` brings the corpus back to the naming convention;
2. every note is parsed, its effective date computed (``core.dates``) and its
   version recorded; the "description != body" check runs on its history
   (``core.drift``);
3. notes whose content changed are chunked and embedded, the others only get their
   metadata (date) refreshed; notes whose file disappeared are deleted;
4. MEMORY.md (the index loaded whole into every session) is regenerated within its
   line and byte budget.

Models are never mixed: if the embedder's identity differs from the active
generation's, the pass builds a *new* generation (or resumes the one already
building for that identity) instead of writing into the old one, and activates it
once complete (``auto_activate``).
"""
from __future__ import annotations

import datetime
import os
import re
import sys
import threading
import time
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from . import dates, drift
from .config import env, env_bool, env_int, env_list
from . import normalize as normalize_mod
from .contract import DEFAULT_PROJECT, ChunkRecord, Generation, NoteRecord
from .notes import INDEX_FILENAME, filename_for, parse_links, parse_note
from .scope import project_of, valid_project

CHUNK_TARGET = 1200     # chars; pack paragraphs up to this size
EMBED_BATCH = 64
INDEX_MAX_BYTES = 24_000  # the harness truncates MEMORY.md past ~24.4 KB…
INDEX_MAX_LINES = 190     # …and loads only its first 200 lines
RECENT_DAYS = 21
INDEX_HEADER = ("<!-- Generated by the memory indexer from the notes' descriptions — do not edit "
                "by hand. Overview only: read the notes with memory_search / memory_get. -->\n\n")


# ---------------------------------------------------------------- chunking

_SENTENCE_END = re.compile(r"(?<=[.!?…:;])[\"')\]»]*\s+(?=[\"'(«\[*_`#>-]?[A-Z0-9À-Ý])")


def _split_long(text: str, limit: int) -> list[str]:
    """Pieces of ``text`` of at most ``limit`` chars: lines, then sentences, then words."""
    if len(text) <= limit:
        return [text]
    lines = [ln for ln in text.split("\n") if ln.strip()]
    if len(lines) > 1:
        units = lines
        sep = "\n"
    else:
        units = [s for s in _SENTENCE_END.split(text) if s.strip()]
        sep = " "
        if len(units) <= 1:
            words, units, cur = text.split(), [], ""
            for w in words:
                while len(w) > limit:           # one unbreakable token (URL, base64…)
                    if cur:
                        units.append(cur)
                        cur = ""
                    units.append(w[:limit])
                    w = w[limit:]
                if cur and len(cur) + 1 + len(w) > limit:
                    units.append(cur)
                    cur = w
                else:
                    cur = f"{cur} {w}" if cur else w
            if cur:
                units.append(cur)
            return units
    out: list[str] = []
    for u in units:
        out.extend(_split_long(u.strip(), limit))
    return _pack(out, limit, sep)


def _pack(pieces: list[str], limit: int, sep: str) -> list[str]:
    chunks: list[str] = []
    cur = ""
    for p in pieces:
        if cur and len(cur) + len(sep) + len(p) > limit:
            chunks.append(cur)
            cur = p
        else:
            cur = f"{cur}{sep}{p}" if cur else p
    if cur:
        chunks.append(cur)
    return chunks


def chunk_body(body: str, target: int = CHUNK_TARGET) -> list[str]:
    """Chunks of at most ``target`` chars, cut on paragraphs, then lines, then
    sentences (a 2.x chunk could be any size: one long paragraph = one chunk)."""
    body = (body or "").strip()
    if not body:
        return []
    if len(body) <= target:
        return [body]
    pieces: list[str] = []
    for para in (p.strip() for p in re.split(r"\n\s*\n", body)):
        if para:
            pieces.extend(_split_long(para, target))
    return _pack(pieces, target, "\n\n")


def embed_text(name: str, description: str, chunk: str) -> str:
    """Name + description prepended to every chunk: keywords lift recall."""
    return f"{name}. {description}. {chunk}"


# ---------------------------------------------------------------- dead paths

def find_dead_paths(body: str, roots: list[Path], prefixes: tuple[str, ...]) -> list[str]:
    """Repository paths (``<prefix>/…``) quoted by a note that exist in none of ``roots``.

    Run where the indexer runs, against every repository the notes talk about: a
    reviewer that sees only one checkout reports paths of the others as dead.
    """
    if not roots or not prefixes:
        return []
    # not preceded by a word, a path separator or a dot: "/x/.openclaw/openclaw.json" is not
    # the repository path "openclaw/openclaw.json"
    rx = re.compile(r"(?<![\w/.~-])((?:" + "|".join(map(re.escape, prefixes)) + r")/[\w\-./]+)")
    gone = r"(removed|deleted|supprimés?|retirés?|n'existe plus|n'existe pas|décommissionnée?s?)"
    acked = re.compile(r"^[`'\"»\s]*\(" + gone, re.I)
    acked_line = re.compile(gone, re.I)
    found: set[str] = set()
    matches = list(rx.finditer(body))
    tails = []
    for i, m in enumerate(matches):
        # what the note says right after this path (up to the next path, same line)
        stop = min([x for x in (body.find("\n", m.end()), m.end() + 50,
                                matches[i + 1].start() if i + 1 < len(matches) else -1)
                    if x >= 0])
        tails.append(body[m.end():stop])
    connector = re.compile(r"^[`'\"\s,+&/]*(?:\b(?:et|and|ou|or)\b)?[`'\"\s,+&]*$", re.I)

    def gone_after(i: int) -> bool:
        """« `a` + `b` retirés » marks both; « a, b (removed) » marks only b."""
        while True:
            w = acked_line.search(tails[i])
            if w and "(" not in tails[i][:w.start()]:
                return True
            if i + 1 < len(matches) and connector.match(tails[i]):
                i += 1
                continue
            return False

    for i, m in enumerate(matches):
        nxt = body[m.end():m.end() + 60]
        if (nxt[:1] and nxt[:1] in "{*…") or acked.match(nxt) or gone_after(i):
            continue        # a glob, a range ("0001…0011"), or marked as gone in the note
        p = m.group(1).rstrip(".,;:)»'\"`")
        if any(ch in p for ch in "*{<>$…") or p.endswith("/") or p.endswith("-"):
            continue
        if p.count("/") == 1 and "." not in p.split("/")[-1]:
            continue        # "infra/TF", "docs/maic": a folder named in prose, not a file
        found.add(p)
    # A path is reported only when its folder still exists somewhere: the file moved or was
    # deleted next to its siblings. A path whose folder exists nowhere is, far more often, a
    # fragment of prose ("infra/TF"), a path of a repository that is not checked here, or
    # a truncated quote — 9 of the 12 remaining reports on a 415-note corpus (03.10.2026).
    return sorted(p for p in found
                  if not any((r / p).exists() for r in roots)
                  and any((r / p).parent.is_dir() for r in roots))


# ---------------------------------------------------------------- MEMORY.md

_RULE_PREAMBLE = re.compile(
    r"^(?:Rule|Règle|RÈGLE|Principle[^—:]{0,40}?|Principe[^—:]{0,40}?|Pitfall[^—:]{0,40}?|"
    r"Piège[^—:]{0,40}?)\b[^—:]{0,70}?\d{4}\)?[^—:]{0,60}?\s[—:]\s*")


def _hook(text: str) -> str:
    """The description without a "Rule born on <date> (context) —" preamble that would
    eat the whole truncated hook."""
    text = " ".join((text or "").split())
    stripped = _RULE_PREAMBLE.sub("", text, count=1)
    return (stripped[:1].upper() + stripped[1:]) if len(stripped) > 20 else text


def _truncate(text: str, cap: int) -> str:
    if len(text) <= cap:
        return text
    cut = text[: cap - 1]
    sp = cut.rfind(" ")
    if sp > cap // 2:
        cut = cut[:sp]
    return cut.rstrip(" ,;:—-") + "…"


def render_memory_index(
    notes: list[NoteRecord],
    *,
    now: datetime.datetime | None = None,
    max_lines: int = INDEX_MAX_LINES,
    max_bytes: int = INDEX_MAX_BYTES,
    recent_days: int = RECENT_DAYS,
    header: str | None = None,
) -> tuple[str, dict]:
    """MEMORY.md in three tiers, within ``max_lines`` AND ``max_bytes``:

    1. rules (``feedback`` / ``user`` notes) and ``priority`` notes, with their hook:
       they must be read without being searched for;
    2. notes updated in the last ``recent_days`` (effective date), most recent first;
    3. ALL notes grouped by family (first name segment), bare links: the overview
       is exhaustive, no note can drop out of the index silently.

    Past ~200 notes the line budget bites first: one line per note used to cut the
    end of the index without any signal. Levers, in order: recent hooks and count,
    then the length of rule hooks, then one-note families packed on shared lines.
    """
    now = now or dates.utcnow()
    rows = sorted(notes, key=lambda n: n.name.lower())
    header = header if header is not None else INDEX_HEADER
    cutoff = now - datetime.timedelta(days=recent_days)
    rules = [n for n in rows if n.type in ("feedback", "user") or n.priority]
    rule_names = {n.name for n in rules}
    dated = []
    for n in rows:
        if n.name in rule_names:
            continue
        mod = dates.parse_dt(n.modified)
        if mod and mod >= cutoff:
            dated.append((mod, n))
    dated.sort(key=lambda t: t[0], reverse=True)
    recent_all = [n for _m, n in dated]

    families: dict[str, list[NoteRecord]] = {}
    for n in rows:
        families.setdefault(n.name.split("-")[0], []).append(n)

    def link(n: NoteRecord) -> str:
        fname = Path(n.source_path).name
        return n.name if fname == filename_for(n.name) else f"[{n.name}]({fname})"

    family_lines = ["- **{}** — {}".format(fam, " · ".join(link(n) for n in group))
                    for fam, group in sorted(families.items())]
    # last lever: one-note families packed together on a few lines
    singles = [link(g[0]) for _f, g in sorted(families.items()) if len(g) == 1]
    packed = [f"- **{fam}** — {' · '.join(link(n) for n in group)}"
              for fam, group in sorted(families.items()) if len(group) > 1]
    cur = ""
    for s_ in singles:
        if cur and len(cur) + len(s_) > 600:
            packed.append("- " + cur)
            cur = s_
        else:
            cur = f"{cur} · {s_}" if cur else s_
    if cur:
        packed.append("- " + cur)

    hooks = {n.name: _hook(n.description) for n in rows}
    cache: dict[tuple[str, int], str] = {}

    def line(n: NoteRecord, cap: int) -> str:
        key = (n.name, cap)
        if key not in cache:
            star = "★ " if n.priority else ""
            desc = _truncate(hooks[n.name], cap)
            fname = Path(n.source_path).name
            cache[key] = (f"- {star}[{n.name}]({fname}) — {desc}" if desc
                          else f"- {star}[{n.name}]({fname})")
        return cache[key]

    def render(cap: int, n_recent: int, recent_cap: int, fam_lines: list[str]) -> str:
        recent = recent_all[:n_recent]
        title_recent = f"Updated in the last {recent_days} days ({len(recent)}"
        title_recent += (f" of {len(recent_all)}, most recent first)"
                         if len(recent) < len(recent_all) else ")")
        lines: list[str] = []
        if rules:
            lines.append(f"## Working rules ({len(rules)}) — apply them, do not search them\n")
            lines += [line(n, cap) for n in rules] + [""]
        if recent:
            lines.append(f"## {title_recent}\n")
            lines += [line(n, recent_cap) for n in recent] + [""]
        lines.append(f"## All notes by family ({len(rows)}) — file = name with \"_\"\n")
        lines += fam_lines
        return header + "\n".join(lines) + "\n"

    def fits(c: str) -> bool:
        return c.count("\n") <= max_lines and len(c.encode("utf-8")) <= max_bytes

    # largest number of recent notes that fits, by bisection (the size grows with it)
    ok = False
    content, n_kept = render(200, len(recent_all), 80, family_lines), len(recent_all)
    for fam_lines in (family_lines, packed):
        for cap in range(200, 39, -10):
            for rcap in (80, 50):
                if not fits(render(cap, 0, rcap, fam_lines)):
                    continue
                lo, hi = 0, len(recent_all)
                while lo < hi:
                    mid = (lo + hi + 1) // 2
                    if fits(render(cap, mid, rcap, fam_lines)):
                        lo = mid
                    else:
                        hi = mid - 1
                n_kept, content, ok = lo, render(cap, lo, rcap, fam_lines), True
                break
            if ok:
                break
        if ok:
            break
    stats = {"notes": len(rows), "families": len(families), "rules": len(rules),
             "recent": n_kept, "recent_total": len(recent_all), "lines": content.count("\n"),
             "bytes": len(content.encode("utf-8")), "fits": ok}
    return content, stats


# ---------------------------------------------------------------- indexer

@dataclass
class IndexConfig:
    memory_dir: Path
    normalize: bool = True
    grace: int = normalize_mod.DEFAULT_GRACE
    chunk_target: int = CHUNK_TARGET
    write_index: bool = True
    index_filename: str = INDEX_FILENAME
    index_max_lines: int = INDEX_MAX_LINES
    index_max_bytes: int = INDEX_MAX_BYTES
    recent_days: int = RECENT_DAYS
    auto_activate: bool = True
    migrate_mtime: bool = False       # bootstrap dates from file mtimes (2.x migration)
    dead_path_roots: list[Path] = field(default_factory=list)
    dead_path_prefixes: tuple[str, ...] = ()
    index_header: str | None = None
    # 3.2: the project of every note of ``memory_dir`` (one directory = one project). A pass
    # only prunes the notes of its own project.
    project: str = DEFAULT_PROJECT

    @classmethod
    def from_env(cls, **overrides) -> "IndexConfig":
        """``CORTHEXIS_*`` variables (``SOKKAN_*`` read for compatibility)."""
        cfg = cls(
            memory_dir=Path(env("MEMORY_DIR", "~/.corthexis/memory")).expanduser(),
            normalize=env_bool("NORMALIZE", True),
            grace=env_int("NORMALIZE_GRACE", normalize_mod.DEFAULT_GRACE),
            chunk_target=env_int("CHUNK_TARGET", CHUNK_TARGET),
            write_index=env_bool("WRITE_INDEX", True),
            index_filename=env("INDEX_FILENAME", INDEX_FILENAME),
            index_max_lines=env_int("INDEX_MAX_LINES", INDEX_MAX_LINES),
            index_max_bytes=env_int("INDEX_MAX_BYTES", INDEX_MAX_BYTES),
            recent_days=env_int("RECENT_DAYS", RECENT_DAYS),
            auto_activate=env_bool("AUTO_ACTIVATE", True),
            migrate_mtime=env_bool("MIGRATE_MTIME", False),
            dead_path_roots=[Path(p).expanduser() for p in env_list("DEAD_PATH_ROOTS", ":")],
            dead_path_prefixes=tuple(env_list("DEAD_PATH_PREFIXES")),
            project=env("MEMORY_PROJECT", DEFAULT_PROJECT) or DEFAULT_PROJECT,
        )
        for k, v in overrides.items():
            setattr(cfg, k, v)
        return cfg


@dataclass
class IndexReport:
    generation: int | None = None
    built_generation: bool = False    # a new generation was (being) built in this pass
    activated: bool = False
    reindexed: int = 0
    metadata_only: int = 0
    unchanged: int = 0
    pruned: int = 0
    chunks_written: int = 0
    notes: int = 0
    bootstrap: bool = False
    normalize: normalize_mod.Plan | None = None
    date_sources: Counter = field(default_factory=Counter)
    rejuvenated: list[str] = field(default_factory=list)   # body changed in this pass
    drift: list[drift.DriftFinding] = field(default_factory=list)
    dead_paths: dict[str, list[str]] = field(default_factory=dict)
    out_of_convention: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    index_stats: dict = field(default_factory=dict)
    index_written: bool = False


class Indexer:
    def __init__(self, store, embedder, config: IndexConfig, *, clock=dates.utcnow,
                 log=None) -> None:
        self.store = store
        self.embedder = embedder
        self.cfg = config
        self.clock = clock
        self.log = log or (lambda msg: print(msg, file=sys.stderr))

    # -- generations
    def _target_generation(self, rebuild: bool) -> tuple[Generation, bool]:
        ident = self.embedder.identity()
        active = self.store.active_generation()
        if active is not None and active.embed_identity == ident and not rebuild:
            return active, False
        building = [g for g in self.store.generations()
                    if g.status == "building" and g.embed_identity == ident]
        if building and not rebuild:
            return building[-1], True
        probe = self.embedder.embed_docs(["dimension probe"])
        # the dense/lexical blend that suits this model is stored with the generation
        lw = getattr(self.embedder, "lexical_weight", None)
        lw = lw() if callable(lw) else lw
        if lw is not None:
            gen = self.store.create_generation(ident, len(probe[0]), lexical_weight=float(lw))
        else:
            gen = self.store.create_generation(ident, len(probe[0]))
        if active is not None:
            self.log(f"embedding model changed ({active.embed_identity} -> {ident})"
                     if active.embed_identity != ident else "rebuild requested")
            self.log(f"building generation {gen.id} instead of writing into {active.id}")
        return gen, True

    def _embed(self, texts: list[str]) -> list[list[float]]:
        out: list[list[float]] = []
        for i in range(0, len(texts), EMBED_BATCH):
            out.extend(self.embedder.embed_docs(texts[i:i + EMBED_BATCH]))
        return out

    def run(self, *, rebuild: bool = False) -> IndexReport:
        cfg, store = self.cfg, self.store
        if not valid_project(cfg.project):
            raise ValueError(f"invalid project name for the memory directory: {cfg.project!r}")
        if hasattr(store, "for_project"):   # 3.2: names, history and links are per project
            store = store.for_project(cfg.project)
        mem_dir = Path(cfg.memory_dir)
        if not mem_dir.is_dir():
            raise FileNotFoundError(f"memory dir not found: {mem_dir}")
        rep = IndexReport()
        now = self.clock()

        aliases: dict[str, str] = {}
        if cfg.normalize:
            try:
                plan = normalize_mod.run(mem_dir, grace=cfg.grace, now=now.timestamp(),
                                         index_filename=cfg.index_filename)
                rep.normalize = plan
                aliases = plan.hash_aliases
                for a in plan.changes:
                    self.log("normalize: " + a.render())
            except Exception as exc:  # noqa: BLE001 — a failed repair never blocks indexing
                rep.warnings.append(f"normalize failed: {exc!r}")

        gen, building = self._target_generation(rebuild)
        rep.generation, rep.built_generation = gen.id, building
        rep.bootstrap = store.seen_count() == 0
        indexed = store.note_names(gen.id, project=cfg.project)

        files = sorted(p for p in mem_dir.glob("*.md") if p.name != cfg.index_filename)
        seen: dict[str, Path] = {}
        records: list[NoteRecord] = []
        for path in files:
            note = parse_note(path.read_text(encoding="utf-8", errors="replace"), path.name)
            for w in note.warnings:
                rep.warnings.append(f"{path.name}: {w}")
            if note.name in seen:
                rep.warnings.append(f"{path.name}: name '{note.name}' already used by "
                                    f"{seen[note.name].name}, ignored")
                rep.out_of_convention.append(path.name)
                continue
            seen[note.name] = path
            if path.name != filename_for(note.name) or note.fm is None:
                rep.out_of_convention.append(path.name)

            eff = dates.effective_modified(
                store, note, bootstrap=rep.bootstrap, now=now, mtime=path.stat().st_mtime,
                migrate_mtime=cfg.migrate_mtime, hash_aliases=aliases)
            rep.date_sources[eff.source] += 1
            if eff.changed:
                rep.rejuvenated.append(note.name)
            finding = drift.check_note(store, note.name)
            if finding:
                rep.drift.append(finding)
            dead = find_dead_paths(note.body, cfg.dead_path_roots, cfg.dead_path_prefixes)
            if dead:
                rep.dead_paths[note.name] = dead

            rec = NoteRecord(name=note.name, description=note.description, type=note.type,
                             priority=note.priority, source_path=str(path),
                             modified=eff.modified, modified_source=eff.source, body=note.body,
                             project=cfg.project)
            records.append(rec)
            old = store.get_note(note.name) if note.name in indexed else None
            if old is not None and (old.description, old.type, old.priority, old.source_path,
                                    old.body, project_of(old)) == (
                                        rec.description, rec.type, rec.priority,
                                        rec.source_path, rec.body, rec.project):
                if (old.modified, old.modified_source) != (rec.modified, rec.modified_source):
                    store.upsert_note(rec, None, gen.id)
                    rep.metadata_only += 1
                else:
                    rep.unchanged += 1
                continue
            pieces = chunk_body(note.body, cfg.chunk_target)
            if not pieces:
                pieces = [note.description or note.name]
            vecs = self._embed([embed_text(note.name, note.description, c) for c in pieces])
            if any(len(v) != gen.dim for v in vecs):
                raise RuntimeError(f"embedder returned vectors of the wrong size for "
                                   f"generation {gen.id} (expected {gen.dim})")
            store.upsert_note(rec, [ChunkRecord(i, c, v) for i, (c, v)
                                    in enumerate(zip(pieces, vecs))], gen.id)
            if hasattr(store, "set_links"):
                store.set_links(note.name, parse_links(note.body, note.name))
            rep.reindexed += 1
            rep.chunks_written += len(pieces)

        for name in sorted(indexed - set(seen)):
            store.delete_note(name, gen.id)
            rep.pruned += 1
        rep.notes = len(records)

        if building and cfg.auto_activate:
            store.activate_generation(gen.id)
            rep.activated = True
            self.log(f"generation {gen.id} active ({gen.embed_identity}, {gen.dim} dims)")

        if cfg.write_index:
            content, rep.index_stats = render_memory_index(
                records, now=now, max_lines=cfg.index_max_lines,
                max_bytes=cfg.index_max_bytes, recent_days=cfg.recent_days,
                header=cfg.index_header)
            if not rep.index_stats["fits"]:
                rep.warnings.append(
                    f"{cfg.index_filename} over budget ({rep.index_stats['lines']} lines, "
                    f"{rep.index_stats['bytes']} bytes): archive notes")
            index_path = mem_dir / cfg.index_filename
            if not (index_path.exists() and index_path.read_text(encoding="utf-8") == content):
                index_path.write_text(content, encoding="utf-8")
                rep.index_written = True
        return rep


# ---------------------------------------------------------------- runner (watch + periodic)

def corpus_signature(mem_dir: Path, index_filename: str = INDEX_FILENAME) -> tuple:
    """Cheap fingerprint of the corpus: directory mtime (create / rename / delete), number
    of notes, latest file mtime and total size. One ``stat`` per note."""
    mem_dir = Path(mem_dir)
    st = mem_dir.stat()
    n = size = latest = 0
    with os.scandir(mem_dir) as it:
        for e in it:
            if not e.name.endswith(".md") or e.name == index_filename:
                continue
            try:
                s = e.stat()
            except OSError:
                continue
            n += 1
            size += s.st_size
            latest = max(latest, s.st_mtime_ns)
    return (st.st_mtime_ns, n, latest, size)


class IndexRunner:
    """Runs the indexer like the 2.x one did: at start, when the files change (polled
    signature, debounced) and periodically (dates, normalisation grace, model change).

    ``store_factory`` / ``embedder_factory`` are called lazily so that a database or an
    embedding server that is not up yet only delays the first pass."""

    def __init__(self, store_factory, embedder_factory, config: IndexConfig | None = None, *,
                 watch_s: float | None = None, periodic_s: float | None = None,
                 debounce_s: float = 1.0, log=None, on_report=None,
                 activate_first_only: bool = False):
        self.store_factory, self.embedder_factory = store_factory, embedder_factory
        self.cfg = config
        self.watch_s = watch_s if watch_s is not None else float(env("WATCH_S", "3") or 3)
        self.periodic_s = periodic_s if periodic_s is not None else float(
            env("REINDEX_S", "900") or 900)
        self.debounce_s = debounce_s
        self.log = log or (lambda msg: print(f"[corthexis] {msg}", file=sys.stderr))
        self.on_report = on_report
        # True: the runner only ever activates the FIRST generation (new install); any
        # later model change goes through a gated switch (core.switch), never through here.
        # ``embedder_factory`` is then called at every pass and may return None (no
        # embedder serves the active generation: the pass is skipped).
        self.activate_first_only = activate_first_only
        self.last_report: IndexReport | None = None
        self.last_error: str | None = None
        self.last_run: float | None = None
        self.runs = 0
        self._sig = None
        self._retry_at = 0.0
        self._indexer: Indexer | None = None
        self._stop = threading.Event()
        self._kick = threading.Event()
        self._lock = threading.Lock()

    def _get_indexer(self) -> Indexer:
        if self._indexer is None:
            cfg = self.cfg or IndexConfig.from_env()
            self._indexer = Indexer(self.store_factory(), None, cfg, log=self.log)
            if not self.activate_first_only:
                self._indexer.embedder = self.embedder_factory()
        idx = self._indexer
        if self.activate_first_only:
            idx.embedder = self.embedder_factory()
            if idx.embedder is None:
                raise RuntimeError("no embedder serves the active index generation "
                                   "(model change pending: switch the memory profile)")
            idx.cfg.auto_activate = idx.store.active_generation() is None
            active = idx.store.active_generation()
            if active is not None and active.embed_identity != idx.embedder.identity():
                raise RuntimeError(f"the embedder ({idx.embedder.identity()}) does not serve "
                                   f"the active generation ({active.embed_identity}); a model "
                                   "change goes through a memory profile switch")
        return idx

    def run_once(self, *, rebuild: bool = False) -> IndexReport | None:
        """One pass now (serialised with the loop). Errors are kept in ``last_error``."""
        with self._lock:
            try:
                idx = self._get_indexer()
                self._sig = corpus_signature(idx.cfg.memory_dir, idx.cfg.index_filename)
                rep = idx.run(rebuild=rebuild)
                # a pass may rename files (normalisation) or rewrite MEMORY.md: the
                # signature after the pass is the reference, not the one before
                self._sig = corpus_signature(idx.cfg.memory_dir, idx.cfg.index_filename)
                self.last_report, self.last_error = rep, None
                self.last_run = time.time()
                self.runs += 1
                if rep.reindexed or rep.pruned or rep.activated:
                    self.log(f"indexed: {rep.reindexed} notes re-embedded, {rep.pruned} pruned, "
                             f"{rep.notes} notes, generation {rep.generation}")
                if self.on_report:
                    self.on_report(rep)
                return rep
            except FileNotFoundError as e:
                self.last_error = str(e)        # no note written yet
            except Exception as e:  # noqa: BLE001 — retried at the next tick
                self.last_error = repr(e)
                self.log(f"memory index failed: {e!r}")
            return None

    def changed(self) -> bool:
        cfg = self.cfg or (self._indexer.cfg if self._indexer else IndexConfig.from_env())
        try:
            return corpus_signature(cfg.memory_dir, cfg.index_filename) != self._sig
        except FileNotFoundError:
            return False

    def kick(self) -> None:
        """Ask the loop for a pass now (API "reindex")."""
        self._kick.set()

    def stop(self) -> None:
        self._stop.set()
        self._kick.set()

    def loop(self) -> None:
        self.run_once()
        self._retry_at = time.monotonic() + 30.0
        next_full = time.monotonic() + self.periodic_s
        while not self._stop.is_set():
            kicked = self._kick.wait(self.watch_s)
            if self._stop.is_set():
                break
            self._kick.clear()
            due = time.monotonic() >= next_full
            if self.last_error and not kicked and time.monotonic() < self._retry_at:
                continue                        # failed pass: retry at most every 30 s
            if kicked or due or self.changed():
                if not kicked and not due:
                    # debounce: a session writing several notes = one pass
                    while True:
                        time.sleep(self.debounce_s)
                        before = self._sig
                        try:
                            cfg = self.cfg or self._get_indexer().cfg
                            now_sig = corpus_signature(cfg.memory_dir, cfg.index_filename)
                        except Exception:  # noqa: BLE001
                            break
                        self._sig = now_sig
                        if now_sig == before or self._stop.is_set():
                            break
                self.run_once()
                next_full = time.monotonic() + self.periodic_s
                self._retry_at = time.monotonic() + 30.0

    def start(self) -> threading.Thread:
        t = threading.Thread(target=self.loop, daemon=True, name="corthexis-index")
        t.start()
        return t

    def status(self) -> dict:
        rep = self.last_report
        return {
            "runs": self.runs, "last_run": self.last_run, "last_error": self.last_error,
            "watch_s": self.watch_s, "periodic_s": self.periodic_s,
            "last": None if rep is None else {
                "generation": rep.generation, "notes": rep.notes, "reindexed": rep.reindexed,
                "metadata_only": rep.metadata_only, "unchanged": rep.unchanged,
                "pruned": rep.pruned, "activated": rep.activated,
                "normalized": len(rep.normalize.changes) if rep.normalize else 0,
                "warnings": rep.warnings[:50], "drift": len(rep.drift),
                "date_sources": dict(rep.date_sources)},
        }


def _report_text(rep: IndexReport) -> str:
    lines = [f"generation {rep.generation}{' (new, activated)' if rep.activated else ''}: "
             f"{rep.notes} notes — {rep.reindexed} re-embedded ({rep.chunks_written} chunks), "
             f"{rep.metadata_only} dates refreshed, {rep.unchanged} unchanged, "
             f"{rep.pruned} pruned"]
    if rep.normalize and rep.normalize.changes:
        lines.append(f"normalised: {len(rep.normalize.changes)} change(s)")
    if rep.date_sources:
        lines.append("dates: " + ", ".join(f"{k} {v}" for k, v in sorted(rep.date_sources.items())))
    for w in rep.warnings[:20]:
        lines.append(f"warning: {w}")
    if rep.drift:
        lines.append(f"description != body: {len(rep.drift)} note(s)")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """``python -m core.indexer [--watch] [--rebuild] [--memory-dir DIR] [--json]``"""
    import argparse
    import json

    ap = argparse.ArgumentParser(prog="python -m core.indexer",
                                 description="Index the memory notes into the store.")
    ap.add_argument("--memory-dir", help="notes directory (CORTHEXIS_MEMORY_DIR)")
    ap.add_argument("--watch", action="store_true",
                    help="keep running: reindex on file changes and periodically")
    ap.add_argument("--rebuild", action="store_true", help="build a new generation")
    ap.add_argument("--no-normalize", action="store_true",
                    help="do not repair the naming convention (read-only on the files)")
    ap.add_argument("--no-index-file", action="store_true", help="do not write MEMORY.md")
    ap.add_argument("--json", action="store_true", help="print the report as JSON")
    a = ap.parse_args(argv)

    from . import embed
    from .store import Store

    over = {}
    if a.memory_dir:
        over["memory_dir"] = Path(a.memory_dir).expanduser()
    if a.no_normalize:
        over["normalize"] = False
    if a.no_index_file:
        over["write_index"] = False
    cfg = IndexConfig.from_env(**over)
    runner = IndexRunner(lambda: Store(), embed.get, cfg)
    if a.watch:
        runner.loop()
        return 0
    rep = runner.run_once(rebuild=a.rebuild)
    if rep is None:
        print(f"error: {runner.last_error}", file=sys.stderr)
        return 1
    print(json.dumps(runner.status()["last"], indent=1) if a.json else _report_text(rep))
    return 0


if __name__ == "__main__":
    sys.exit(main())
