"""Incremental indexer of a memory corpus, written against the ``Store`` interface.

One pass:

1. (optional) ``core.normalize`` brings the corpus back to the naming convention;
2. every note is parsed, its effective date computed (``core.dates``) and its
   version recorded; the "description != body" check runs on its history
   (``core.drift``);
3. notes whose content changed are chunked and embedded, the others only get their
   metadata (date) refreshed; notes whose file disappeared are deleted;
4. MEMORY.md (the index loaded whole into every session) is regenerated within its
   line and byte budget.

Models are never mixed: if the embedder's identity differs from the active
generation's, the pass builds a *new* generation (or resumes the one already
building for that identity) instead of writing into the old one, and activates it
once complete (``auto_activate``).
"""
from __future__ import annotations

import datetime
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from . import dates, drift
from .config import env, env_bool, env_int, env_list
from . import normalize as normalize_mod
from .contract import ChunkRecord, Generation, NoteRecord
from .notes import INDEX_FILENAME, filename_for, parse_links, parse_note

CHUNK_TARGET = 1200     # chars; pack paragraphs up to this size
EMBED_BATCH = 64
INDEX_MAX_BYTES = 24_000  # the harness truncates MEMORY.md past ~24.4 KB…
INDEX_MAX_LINES = 190     # …and loads only its first 200 lines
RECENT_DAYS = 21
INDEX_HEADER = ("<!-- Generated by the memory indexer from the notes' descriptions — do not edit "
                "by hand. Overview only: read the notes with memory_search / memory_get. -->\n\n")


# ---------------------------------------------------------------- chunking

_SENTENCE_END = re.compile(r"(?<=[.!?…:;])[\"')\]»]*\s+(?=[\"'(«\[*_`#>-]?[A-Z0-9À-Ý])")


def _split_long(text: str, limit: int) -> list[str]:
    """Pieces of ``text`` of at most ``limit`` chars: lines, then sentences, then words."""
    if len(text) <= limit:
        return [text]
    lines = [ln for ln in text.split("\n") if ln.strip()]
    if len(lines) > 1:
        units = lines
        sep = "\n"
    else:
        units = [s for s in _SENTENCE_END.split(text) if s.strip()]
        sep = " "
        if len(units) <= 1:
            words, units, cur = text.split(), [], ""
            for w in words:
                while len(w) > limit:           # one unbreakable token (URL, base64…)
                    if cur:
                        units.append(cur)
                        cur = ""
                    units.append(w[:limit])
                    w = w[limit:]
                if cur and len(cur) + 1 + len(w) > limit:
                    units.append(cur)
                    cur = w
                else:
                    cur = f"{cur} {w}" if cur else w
            if cur:
                units.append(cur)
            return units
    out: list[str] = []
    for u in units:
        out.extend(_split_long(u.strip(), limit))
    return _pack(out, limit, sep)


def _pack(pieces: list[str], limit: int, sep: str) -> list[str]:
    chunks: list[str] = []
    cur = ""
    for p in pieces:
        if cur and len(cur) + len(sep) + len(p) > limit:
            chunks.append(cur)
            cur = p
        else:
            cur = f"{cur}{sep}{p}" if cur else p
    if cur:
        chunks.append(cur)
    return chunks


def chunk_body(body: str, target: int = CHUNK_TARGET) -> list[str]:
    """Chunks of at most ``target`` chars, cut on paragraphs, then lines, then
    sentences (a 2.x chunk could be any size: one long paragraph = one chunk)."""
    body = (body or "").strip()
    if not body:
        return []
    if len(body) <= target:
        return [body]
    pieces: list[str] = []
    for para in (p.strip() for p in re.split(r"\n\s*\n", body)):
        if para:
            pieces.extend(_split_long(para, target))
    return _pack(pieces, target, "\n\n")


def embed_text(name: str, description: str, chunk: str) -> str:
    """Name + description prepended to every chunk: keywords lift recall."""
    return f"{name}. {description}. {chunk}"


# ---------------------------------------------------------------- dead paths

def find_dead_paths(body: str, roots: list[Path], prefixes: tuple[str, ...]) -> list[str]:
    """Repository paths (``<prefix>/…``) quoted by a note that exist in none of ``roots``.

    Run where the indexer runs, against every repository the notes talk about: a
    reviewer that sees only one checkout reports paths of the others as dead.
    """
    if not roots or not prefixes:
        return []
    rx = re.compile(r"(?<![\w/])((?:" + "|".join(map(re.escape, prefixes)) + r")/[\w\-./]+)")
    acked = re.compile(r"^[`'\"»\s]*\((removed|deleted|supprimé|n'existe pas|décommissionné)",
                       re.I)
    found: set[str] = set()
    for m in rx.finditer(body):
        nxt = body[m.end():m.end() + 60]
        if nxt[:1] in "{*" or acked.match(nxt):
            continue                    # a glob, or already marked as gone in the note
        p = m.group(1).rstrip(".,;:)»'\"`")
        if any(ch in p for ch in "*{<>$…") or p.endswith("/"):
            continue
        found.add(p)
    return sorted(p for p in found if not any((r / p).exists() for r in roots))


# ---------------------------------------------------------------- MEMORY.md

_RULE_PREAMBLE = re.compile(
    r"^(?:Rule|Règle|RÈGLE|Principle[^—:]{0,40}?|Principe[^—:]{0,40}?|Pitfall[^—:]{0,40}?|"
    r"Piège[^—:]{0,40}?)\b[^—:]{0,70}?\d{4}\)?[^—:]{0,60}?\s[—:]\s*")


def _hook(text: str) -> str:
    """The description without a "Rule born on <date> (context) —" preamble that would
    eat the whole truncated hook."""
    text = " ".join((text or "").split())
    stripped = _RULE_PREAMBLE.sub("", text, count=1)
    return (stripped[:1].upper() + stripped[1:]) if len(stripped) > 20 else text


def _truncate(text: str, cap: int) -> str:
    if len(text) <= cap:
        return text
    cut = text[: cap - 1]
    sp = cut.rfind(" ")
    if sp > cap // 2:
        cut = cut[:sp]
    return cut.rstrip(" ,;:—-") + "…"


def render_memory_index(
    notes: list[NoteRecord],
    *,
    now: datetime.datetime | None = None,
    max_lines: int = INDEX_MAX_LINES,
    max_bytes: int = INDEX_MAX_BYTES,
    recent_days: int = RECENT_DAYS,
    header: str | None = None,
) -> tuple[str, dict]:
    """MEMORY.md in three tiers, within ``max_lines`` AND ``max_bytes``:

    1. rules (``feedback`` / ``user`` notes) and ``priority`` notes, with their hook:
       they must be read without being searched for;
    2. notes updated in the last ``recent_days`` (effective date), most recent first;
    3. ALL notes grouped by family (first name segment), bare links: the overview
       is exhaustive, no note can drop out of the index silently.

    Past ~200 notes the line budget bites first: one line per note used to cut the
    end of the index without any signal. Levers, in order: recent hooks and count,
    then the length of rule hooks, then one-note families packed on shared lines.
    """
    now = now or dates.utcnow()
    rows = sorted(notes, key=lambda n: n.name.lower())
    header = header if header is not None else INDEX_HEADER
    cutoff = now - datetime.timedelta(days=recent_days)
    rules = [n for n in rows if n.type in ("feedback", "user") or n.priority]
    rule_names = {n.name for n in rules}
    dated = []
    for n in rows:
        if n.name in rule_names:
            continue
        mod = dates.parse_dt(n.modified)
        if mod and mod >= cutoff:
            dated.append((mod, n))
    dated.sort(key=lambda t: t[0], reverse=True)
    recent_all = [n for _m, n in dated]

    families: dict[str, list[NoteRecord]] = {}
    for n in rows:
        families.setdefault(n.name.split("-")[0], []).append(n)

    def link(n: NoteRecord) -> str:
        fname = Path(n.source_path).name
        return n.name if fname == filename_for(n.name) else f"[{n.name}]({fname})"

    family_lines = ["- **{}** — {}".format(fam, " · ".join(link(n) for n in group))
                    for fam, group in sorted(families.items())]
    # last lever: one-note families packed together on a few lines
    singles = [link(g[0]) for _f, g in sorted(families.items()) if len(g) == 1]
    packed = [f"- **{fam}** — {' · '.join(link(n) for n in group)}"
              for fam, group in sorted(families.items()) if len(group) > 1]
    cur = ""
    for s_ in singles:
        if cur and len(cur) + len(s_) > 600:
            packed.append("- " + cur)
            cur = s_
        else:
            cur = f"{cur} · {s_}" if cur else s_
    if cur:
        packed.append("- " + cur)

    hooks = {n.name: _hook(n.description) for n in rows}
    cache: dict[tuple[str, int], str] = {}

    def line(n: NoteRecord, cap: int) -> str:
        key = (n.name, cap)
        if key not in cache:
            star = "★ " if n.priority else ""
            desc = _truncate(hooks[n.name], cap)
            fname = Path(n.source_path).name
            cache[key] = (f"- {star}[{n.name}]({fname}) — {desc}" if desc
                          else f"- {star}[{n.name}]({fname})")
        return cache[key]

    def render(cap: int, n_recent: int, recent_cap: int, fam_lines: list[str]) -> str:
        recent = recent_all[:n_recent]
        title_recent = f"Updated in the last {recent_days} days ({len(recent)}"
        title_recent += (f" of {len(recent_all)}, most recent first)"
                         if len(recent) < len(recent_all) else ")")
        lines: list[str] = []
        if rules:
            lines.append(f"## Working rules ({len(rules)}) — apply them, do not search them\n")
            lines += [line(n, cap) for n in rules] + [""]
        if recent:
            lines.append(f"## {title_recent}\n")
            lines += [line(n, recent_cap) for n in recent] + [""]
        lines.append(f"## All notes by family ({len(rows)}) — file = name with \"_\"\n")
        lines += fam_lines
        return header + "\n".join(lines) + "\n"

    def fits(c: str) -> bool:
        return c.count("\n") <= max_lines and len(c.encode("utf-8")) <= max_bytes

    # largest number of recent notes that fits, by bisection (the size grows with it)
    ok = False
    content, n_kept = render(200, len(recent_all), 80, family_lines), len(recent_all)
    for fam_lines in (family_lines, packed):
        for cap in range(200, 39, -10):
            for rcap in (80, 50):
                if not fits(render(cap, 0, rcap, fam_lines)):
                    continue
                lo, hi = 0, len(recent_all)
                while lo < hi:
                    mid = (lo + hi + 1) // 2
                    if fits(render(cap, mid, rcap, fam_lines)):
                        lo = mid
                    else:
                        hi = mid - 1
                n_kept, content, ok = lo, render(cap, lo, rcap, fam_lines), True
                break
            if ok:
                break
        if ok:
            break
    stats = {"notes": len(rows), "families": len(families), "rules": len(rules),
             "recent": n_kept, "recent_total": len(recent_all), "lines": content.count("\n"),
             "bytes": len(content.encode("utf-8")), "fits": ok}
    return content, stats


# ---------------------------------------------------------------- indexer

@dataclass
class IndexConfig:
    memory_dir: Path
    normalize: bool = True
    grace: int = normalize_mod.DEFAULT_GRACE
    chunk_target: int = CHUNK_TARGET
    write_index: bool = True
    index_filename: str = INDEX_FILENAME
    index_max_lines: int = INDEX_MAX_LINES
    index_max_bytes: int = INDEX_MAX_BYTES
    recent_days: int = RECENT_DAYS
    auto_activate: bool = True
    migrate_mtime: bool = False       # bootstrap dates from file mtimes (2.x migration)
    dead_path_roots: list[Path] = field(default_factory=list)
    dead_path_prefixes: tuple[str, ...] = ()
    index_header: str | None = None

    @classmethod
    def from_env(cls, **overrides) -> "IndexConfig":
        """``CORTHEXIS_*`` variables (``SOKKAN_*`` read for compatibility)."""
        cfg = cls(
            memory_dir=Path(env("MEMORY_DIR", "~/.corthexis/memory")).expanduser(),
            normalize=env_bool("NORMALIZE", True),
            grace=env_int("NORMALIZE_GRACE", normalize_mod.DEFAULT_GRACE),
            chunk_target=env_int("CHUNK_TARGET", CHUNK_TARGET),
            write_index=env_bool("WRITE_INDEX", True),
            index_filename=env("INDEX_FILENAME", INDEX_FILENAME),
            index_max_lines=env_int("INDEX_MAX_LINES", INDEX_MAX_LINES),
            index_max_bytes=env_int("INDEX_MAX_BYTES", INDEX_MAX_BYTES),
            recent_days=env_int("RECENT_DAYS", RECENT_DAYS),
            auto_activate=env_bool("AUTO_ACTIVATE", True),
            migrate_mtime=env_bool("MIGRATE_MTIME", False),
            dead_path_roots=[Path(p).expanduser() for p in env_list("DEAD_PATH_ROOTS", ":")],
            dead_path_prefixes=tuple(env_list("DEAD_PATH_PREFIXES")),
        )
        for k, v in overrides.items():
            setattr(cfg, k, v)
        return cfg


@dataclass
class IndexReport:
    generation: int | None = None
    built_generation: bool = False    # a new generation was (being) built in this pass
    activated: bool = False
    reindexed: int = 0
    metadata_only: int = 0
    unchanged: int = 0
    pruned: int = 0
    chunks_written: int = 0
    notes: int = 0
    bootstrap: bool = False
    normalize: normalize_mod.Plan | None = None
    date_sources: Counter = field(default_factory=Counter)
    rejuvenated: list[str] = field(default_factory=list)   # body changed in this pass
    drift: list[drift.DriftFinding] = field(default_factory=list)
    dead_paths: dict[str, list[str]] = field(default_factory=dict)
    out_of_convention: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    index_stats: dict = field(default_factory=dict)
    index_written: bool = False


class Indexer:
    def __init__(self, store, embedder, config: IndexConfig, *, clock=dates.utcnow,
                 log=None) -> None:
        self.store = store
        self.embedder = embedder
        self.cfg = config
        self.clock = clock
        self.log = log or (lambda msg: print(msg, file=sys.stderr))

    # -- generations
    def _target_generation(self, rebuild: bool) -> tuple[Generation, bool]:
        ident = self.embedder.identity()
        active = self.store.active_generation()
        if active is not None and active.embed_identity == ident and not rebuild:
            return active, False
        building = [g for g in self.store.generations()
                    if g.status == "building" and g.embed_identity == ident]
        if building and not rebuild:
            return building[-1], True
        probe = self.embedder.embed_docs(["dimension probe"])
        gen = self.store.create_generation(ident, len(probe[0]))
        if active is not None:
            self.log(f"embedding model changed ({active.embed_identity} -> {ident})"
                     if active.embed_identity != ident else "rebuild requested")
            self.log(f"building generation {gen.id} instead of writing into {active.id}")
        return gen, True

    def _embed(self, texts: list[str]) -> list[list[float]]:
        out: list[list[float]] = []
        for i in range(0, len(texts), EMBED_BATCH):
            out.extend(self.embedder.embed_docs(texts[i:i + EMBED_BATCH]))
        return out

    def run(self, *, rebuild: bool = False) -> IndexReport:
        cfg, store = self.cfg, self.store
        mem_dir = Path(cfg.memory_dir)
        if not mem_dir.is_dir():
            raise FileNotFoundError(f"memory dir not found: {mem_dir}")
        rep = IndexReport()
        now = self.clock()

        aliases: dict[str, str] = {}
        if cfg.normalize:
            try:
                plan = normalize_mod.run(mem_dir, grace=cfg.grace, now=now.timestamp(),
                                         index_filename=cfg.index_filename)
                rep.normalize = plan
                aliases = plan.hash_aliases
                for a in plan.changes:
                    self.log("normalize: " + a.render())
            except Exception as exc:  # noqa: BLE001 — a failed repair never blocks indexing
                rep.warnings.append(f"normalize failed: {exc!r}")

        gen, building = self._target_generation(rebuild)
        rep.generation, rep.built_generation = gen.id, building
        rep.bootstrap = store.seen_count() == 0
        indexed = store.note_names(gen.id)

        files = sorted(p for p in mem_dir.glob("*.md") if p.name != cfg.index_filename)
        seen: dict[str, Path] = {}
        records: list[NoteRecord] = []
        for path in files:
            note = parse_note(path.read_text(encoding="utf-8", errors="replace"), path.name)
            for w in note.warnings:
                rep.warnings.append(f"{path.name}: {w}")
            if note.name in seen:
                rep.warnings.append(f"{path.name}: name '{note.name}' already used by "
                                    f"{seen[note.name].name}, ignored")
                rep.out_of_convention.append(path.name)
                continue
            seen[note.name] = path
            if path.name != filename_for(note.name) or note.fm is None:
                rep.out_of_convention.append(path.name)

            eff = dates.effective_modified(
                store, note, bootstrap=rep.bootstrap, now=now, mtime=path.stat().st_mtime,
                migrate_mtime=cfg.migrate_mtime, hash_aliases=aliases)
            rep.date_sources[eff.source] += 1
            if eff.changed:
                rep.rejuvenated.append(note.name)
            finding = drift.check_note(store, note.name)
            if finding:
                rep.drift.append(finding)
            dead = find_dead_paths(note.body, cfg.dead_path_roots, cfg.dead_path_prefixes)
            if dead:
                rep.dead_paths[note.name] = dead

            rec = NoteRecord(name=note.name, description=note.description, type=note.type,
                             priority=note.priority, source_path=str(path),
                             modified=eff.modified, modified_source=eff.source, body=note.body)
            records.append(rec)
            old = store.get_note(note.name) if note.name in indexed else None
            if old is not None and (old.description, old.type, old.priority, old.source_path,
                                    old.body) == (rec.description, rec.type, rec.priority,
                                                  rec.source_path, rec.body):
                if (old.modified, old.modified_source) != (rec.modified, rec.modified_source):
                    store.upsert_note(rec, None, gen.id)
                    rep.metadata_only += 1
                else:
                    rep.unchanged += 1
                continue
            pieces = chunk_body(note.body, cfg.chunk_target)
            if not pieces:
                pieces = [note.description or note.name]
            vecs = self._embed([embed_text(note.name, note.description, c) for c in pieces])
            if any(len(v) != gen.dim for v in vecs):
                raise RuntimeError(f"embedder returned vectors of the wrong size for "
                                   f"generation {gen.id} (expected {gen.dim})")
            store.upsert_note(rec, [ChunkRecord(i, c, v) for i, (c, v)
                                    in enumerate(zip(pieces, vecs))], gen.id)
            if hasattr(store, "set_links"):
                store.set_links(note.name, parse_links(note.body, note.name))
            rep.reindexed += 1
            rep.chunks_written += len(pieces)

        for name in sorted(indexed - set(seen)):
            store.delete_note(name, gen.id)
            rep.pruned += 1
        rep.notes = len(records)

        if building and cfg.auto_activate:
            store.activate_generation(gen.id)
            rep.activated = True
            self.log(f"generation {gen.id} active ({gen.embed_identity}, {gen.dim} dims)")

        if cfg.write_index:
            content, rep.index_stats = render_memory_index(
                records, now=now, max_lines=cfg.index_max_lines,
                max_bytes=cfg.index_max_bytes, recent_days=cfg.recent_days,
                header=cfg.index_header)
            if not rep.index_stats["fits"]:
                rep.warnings.append(
                    f"{cfg.index_filename} over budget ({rep.index_stats['lines']} lines, "
                    f"{rep.index_stats['bytes']} bytes): archive notes")
            index_path = mem_dir / cfg.index_filename
            if not (index_path.exists() and index_path.read_text(encoding="utf-8") == content):
                index_path.write_text(content, encoding="utf-8")
                rep.index_written = True
        return rep
